apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: knitting-crab-coordinator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: knitting-crab-coordinator
      spec:
        replicas: 3
  - target:
      kind: ConfigMap
      name: knitting-crab-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: knitting-crab-config
      data:
        RUST_LOG: "info,knitting_crab_coordinator=info"
