apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: knitting-crab-system

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: knitting-crab
      app.kubernetes.io/component: coordinator
      app.kubernetes.io/managed-by: flux

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
